#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

determine_os_type () {
  if [[ -f '/etc/lsb-release' ]]; then
    source '/etc/lsb-release'
  else
    fail "Unable to determine OS Type"
  fi
}

install_pkgs () {
  if [[ `type -P apt-get` ]]; then
    packages_to_install=("wget" "tmux" "curl" "vim" "git" "nmap" "rsync" "mtr-tiny" "iftop" "ipcalc" "tmux" "htop" "ruby" "python3" "python3-setuptools" "gcc" "make" "build-essential" "linux-headers-`uname -r`" "socat" "python3-psutil" "python3-pip" "python3-pygit2")

    info "Installing packages from apt: ${packages_to_install[@]}"
    sudo apt-get install ${packages_to_install[@]} -y
  else
    fail "Unable to locate apt"
  fi
}

install_rvm () {
  if ! [[ `type -P rvm` ]]; then
    echo "Installing rvm"
    \curl -sSL https://get.rvm.io | bash -s stable
  fi
}

install_ruby_versions () {
  if [[ `type -P rvm` ]]; then
    rubies_to_install=("2.2")

    for installing_ruby in "${rubies_to_install[@]}"; do
      info "Installing ${installing_ruby} with rvm"
      rvm install "${installing_ruby}"
    done
  else
    fail "Unable to locate rvm"
  fi
}

install_python_virtualenv () {
  if [[ `type -P python` ]]; then
    if [[ `type -P pip3` ]]; then
      info "installing python virtualenv"
      sudo pip3 install virtualenv
    else
      fail "Unable to locate pip"
    fi
  else
    fail "Unable to locate python"
  fi
}

install_pip_packages () {
  if [[ `type -P python` ]]; then
    if [[ `type -P pip3` ]]; then
      packages_to_install=("pyuv" "powerline-status")

      info "Installing python packages via pip: ${packages_to_install[@]}"
      sudo pip3 install ${packages_to_install[@]}
      sudo pip install ${packages_to_install[@]}
    else
      fail "Unable to locate pip"
    fi
  else
      fail "Unable to locate python"
  fi
}

install_fonts () {
  info "Installing patched fonts for powerline"
  pushd /tmp
  wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
  wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

  mkdir -p "${HOME}/.fonts/truetype/powerline"
  mv PowerlineSymbols.otf "${HOME}/.fonts/truetype/powerline/"
  fc-cache -vf ~/.fonts/

  mkdir -p "${HOME}/.config/fontconfig/conf.d"
  mv 10-powerline-symbols.conf "${HOME}/.config/fontconfig/conf.d/"
  popd
}

determine_os_type

if [[ "${DISTRIB_ID}" == 'Ubuntu' ]]; then
  install_pkgs
  install_rvm
  install_ruby_versions
  install_python_virtualenv
  install_pip_packages
  install_fonts
else
  fail "This can only be run on Ubuntu"
fi
