#!/usr/bin/env bash

# install rvm for the current user
install_rvm () {
    if ! [[ `type -P rvm` ]]; then
        sh -c '\curl -L https://get.rvm.io | bash -s stable'
    fi
}

# install brew
install_brew () {
    if ! [[ `type -P brew` ]]; then
        ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
    fi
}

install_rvm
install_brew